* dida.el - 在 Emacs 中与滴答清单(Dida365)同步

Dida.el 是一个 Emacs 插件，旨在通过滴答清单（Dida365）官方提供的 API，实现 Emacs Org mode 与滴答清单之间的数据同步。

本插件依赖于以下 Emacs 包：
- [[https://github.com/alphapapa/plz.el][plz]]: 用于发送 HTTP 请求。
- [[https://github.com/jwiegley/emacs-async][async]]: 用于执行异步网络操作，避免在同步时冻结 Emacs。
- [[https://github.com/magnars/s.el][s.el]]: 用于字符串处理。

** 特性 (Features)
- *双向同步* ：通过独立的 =fetch= (拉取) 和 =push= (推送) 命令，实现与滴答清单的双向同步。具体支持的同步指令：覆盖本地、删除任务、更新任务。 *不支持新建任务* 
- *Org 格式映射* ：
  - 滴答清单的“清单(Project)”映射为 Org 文件的一级标题。
  - “任务(Task)”映射为二级标题。
  - 支持任务状态 (=TODO= / =DONE=)、优先级 (=[#A]=, =[#B]= , =[#C]= )、内容/备注。
  - 支持任务的日期 (=SCHEDULED=) 和重复属性。
- *安全认证* ：使用标准的 OAuth2.0 协议进行授权，确保账户安全。
- async方式push，不阻塞emacs

** 安装 (Installation)
推荐使用 =use-package= 进行管理。请确保您已经安装了 =plz=, =async= 和 =s.el= 。

#+BEGIN_SRC emacs-lisp
;; 确保依赖已安装
;; (package-install 'plz)
;; (package-install 'async)
;; (package-install 's.el)

(use-package dida :demand t
  :vc (:url "git@github.com:TomoeMami/dida"
            :rev :newest))

#+END_SRC

** 配置 (Configuration)
在使用前，您需要完成以下三个步骤的配置。

*** 第一步：申请 Dida365 API 凭证

1. 访问 [[https://dida365.com/developers][滴答清单开放平台]] 并登录您的账户。
2. 创建一个新的应用。
3. 在应用设置中，您需要填写 *OAuth Redirect URI* 。为了使本插件正常工作，请务必将其设置为：
   #+BEGIN_EXAMPLE
   http://localhost:1145
   #+END_EXAMPLE
4. 创建成功后，您会得到应用的 =Client ID= 和 =Client Secret= 。请将它们妥善保管。

*** 第二步：在 Emacs 中设置变量

将您在上一步获得的凭证和您希望用于同步的本地 Org 文件路径填入 Emacs 配置中。

#+BEGIN_SRC emacs-lisp
(use-package dida :demand t
  :vc (:url "git@github.com:TomoeMami/dida"
            :rev :newest)
  :config
  (setq dida-client-id "YOUR CLIENT ID")
  (setq dida-client-secret "YOUR SECRET")
  (setq dida-sync-file "path/to/your/dida/file"))
#+END_SRC

*** 第三步：授权

首次使用时，您需要对本应用进行授权，以获取访问令牌 (Token)。

1.  在 Emacs 中运行命令 =M-x dida-authorize= 。
2.  Emacs 会自动打开您的默认浏览器，并跳转到滴答清单的授权页面。
3.  请在该页面登录并点击“授权”。
4.  授权成功后，浏览器会跳转到一个本地页面 (localhost:1145)，并显示 "Code copied to kill-ring..."。同时，授权所需的 =code= 已被复制到您的系统剪贴板。
5.  切回 Emacs，在 minibuffer 的提示 "请粘贴code: " 后，使用 =C-y= (yank) 粘贴 =code= 并回车。
6.  如果一切顺利，您会看到 "验证成功！" 的消息。您的访问令牌会被保存在 =~/.emacs.d/didatoken= (默认路径) 文件中，插件会自动处理后续的令牌刷新。

** 使用 (Usage)
为方便使用，建议参考以下设置：

#+begin_src elisp
(use-package dida :demand t
  :vc (:url "git@github.com:TomoeMami/dida"
            :rev :newest)
  :config
  (setq dida-client-id "YOURCLIENT ID")
  (setq dida-client-secret "YOUR SECRET")
  (setq dida-sync-file "path/to/your/dida/file")
  (run-with-idle-timer 60 t #'dida-fetch)
  (add-hook 'org-trigger-hook #'dida-push)
  (add-hook 'after-init-hook #'dida-fetch))
#+end_src

这样一来，在启动后或闲置60秒后，会拉取云端覆盖本地文件；
在任务的todo状态改变时，如果变为了DONE，则会将该任务在云端标记为完成；任何其他行为（包括重复设置为TODO）都会触发一次更新，将本地该任务的相关设置同步到云端。
